cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://www.nfoic.org/themes/custom/nfoic/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  nfoic: 8000
region_wells:
  header: ''
  header_right: ''
  navigation: ''
  navigation_collapsible: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
logo:
  path: themes/custom/nfoic/images/nfoic_2019_logo_flag30_0.png
  url: ''
  use_default: false
navbar_inverse: 1
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
